### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED

### ISSUE THREAD

**Issue by realdengziqi** [wechaty/getting-started#226]
npm start
```
CustomError: ERR_PACKAGE_PATH_NOT_EXPORTED /home/lighthouse/moudle/getting-started-main/node_modules/wechaty-puppet/ ./types /home/lighthouse/moudle/getting-started-main/node_modules/wechaty/dist/esm/src/mods/mod.js
    at throwExportsNotFound (/home/lighthouse/moudle/getting-started-main/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:397:9)
    at packageExportsResolve (/home/lighthouse/moudle/getting-started-main/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:622:3)
    at packageResolve (/home/lighthouse/moudle/getting-started-main/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:763:14)
    at moduleResolve (/home/lighthouse/moudle/getting-started-main/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:815:18)
    at Object.defaultResolve (/home/lighthouse/moudle/getting-started-main/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:929:11)
    at /home/lighthouse/moudle/getting-started-main/node_modules/ts-node/src/esm.ts:152:38
    at Generator.next (<anonymous>)
    at /home/lighthouse/moudle/getting-started-main/node_modules/ts-node/dist/esm.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/lighthouse/moudle/getting-started-main/node_modules/ts-node/dist/esm.js:4:12)

```

**Comment by huan** [comment]
The latest commit should solve your problem.

Please run the below commands and let me know if it fixes this issue:

```sh
rm -fr node_modules package-lock.json
npm install
npm start
```
