### ISSUE TITLE
File '@chatie/tsconfig' not found.

### ISSUE THREAD

**Issue by alexanderqiu** [wechaty/getting-started#236]
/Users/long/.nvm/versions/node/v16.13.1/lib/node_modules/ts-node/src/index.ts:750
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
error TS6053: File '@chatie/tsconfig' not found.

    at createTSError (/Users/long/.nvm/versions/node/v16.13.1/lib/node_modules/ts-node/src/index.ts:750:12)
    at reportTSError (/Users/long/.nvm/versions/node/v16.13.1/lib/node_modules/ts-node/src/index.ts:754:19)
    at create (/Users/long/.nvm/versions/node/v16.13.1/lib/node_modules/ts-node/src/index.ts:765:36)
    at register (/Users/long/.nvm/versions/node/v16.13.1/lib/node_modules/ts-node/src/index.ts:514:15)
    at main (/Users/long/.nvm/versions/node/v16.13.1/lib/node_modules/ts-node/src/bin.ts:250:27)
    at Object.<anonymous> (/Users/long/.nvm/versions/node/v16.13.1/lib/node_modules/ts-node/src/bin.ts:482:3)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  diagnosticText: "\x1B[91merror\x1B[0m\x1B[90m TS6053: \x1B[0mFile '@chatie/tsconfig' not found.\n",
  diagnosticCodes: [ 6053 ]

**Comment by huan** [comment]
Run `npm install` will install all the dependencies for you.
