### ISSUE TITLE
Why is this displayed after logging in to wechat： uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0

### ISSUE THREAD

**Issue by isok001** [wechaty/getting-started#260]
uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (C:\Users\Admin\Desktop\bot\node_modules\wechat4u\lib\util\global.js:69:24)
    at C:\Users\Admin\Desktop\bot\node_modules\wechat4u\lib\core.js:214:24
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
    '    at Object.equal (C:\\Users\\Admin\\Desktop\\bot\\node_modules\\wechat4u\\lib\\util\\global.js:69:24)\n' +
    '    at C:\\Users\\Admin\\Desktop\\bot\\node_modules\\wechat4u\\lib\\core.js:214:24\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}

**Comment by wounddust** [comment]
Me too

**Comment by Mopip77** [comment]
![image](https://user-images.githubusercontent.com/23133662/169735498-7c2dd06b-b9b8-48eb-9150-de673dabc1ab.png)

https://wechaty.js.org/docs/puppet-providers/wechat

Check if your account was registered before 2017.
