### ISSUE TITLE
❓ login failed, This is  error code👉uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0

### ISSUE THREAD

**Issue by 0xc6bd** [wechaty/getting-started#279]
🚨 The issue tracker is not for questions 🚨
```bash
17:32:51 INFO StarterBot onScan: Scanned(3)
uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (D:\projects\wechaty\node_modules\wechat4u\src\util\global.js:53:14)
    at D:\projects\wechaty\node_modules\wechat4u\src\core.js:195:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
    '    at Object.equal (D:\\projects\\wechaty\\node_modules\\wechat4u\\src\\util\\global.js:53:14)\n' +
    '    at D:\\projects\\wechaty\\node_modules\\wechat4u\\src\\core.js:195:16\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}
```
![image](https://user-images.githubusercontent.com/76504395/207560325-21d35e48-b00f-417b-9939-dd224d2eff2a.png)

[question]
node v16.18.1
npm v8.19.2

**Comment by h3clikejava** [comment]
10:01:33 ERR Config process.on(unhandledRejection) promise.catch(Execution context was destroyed, most likely because of a navigation.)
Config GError: Execution context was destroyed, most likely because of a navigation.
    at rewriteError (/home/h3c/Documents/getting-started/node_modules/puppeteer/src/common/ExecutionContext.ts:322:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext._evaluateInternal (/home/h3c/Documents/getting-started/node_modules/puppeteer/src/common/ExecutionContext.ts:271:7)
    at async ExecutionContext.evaluate (/home/h3c/Documents/getting-started/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)
    at async Bridge.proxyWechaty (file:///home/h3c/Documents/getting-started/node_modules/wechaty-puppet-wechat/src/bridge.ts:769:25)
    at async Bridge.getUserName (file:///home/h3c/Documents/getting-started/node_modules/wechaty-puppet-wechat/src/bridge.ts:417:24)
    at async PuppetWeChat.onLogin (file:///home/h3c/Documents/getting-started/node_modules/wechaty-puppet-wechat/src/event.ts:147:20) {
  code: 2,
  details: 'Error: Execution context was destroyed, most likely because of a navigation.\n' +
    '    at rewriteError (/home/h3c/Documents/getting-started/node_modules/puppeteer/src/common/ExecutionContext.ts:322:15)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
    '    at async ExecutionContext._evaluateInternal (/home/h3c/Documents/getting-started/node_modules/puppeteer/src/common/ExecutionContext.ts:271:7)\n' +
    '    at async ExecutionContext.evaluate (/home/h3c/Documents/getting-started/node_modules/puppeteer/src/common/ExecutionContext.ts:140:12)\n' +
    '    at async Bridge.proxyWechaty (file:///home/h3c/Documents/getting-started/node_modules/wechaty-puppet-wechat/src/bridge.ts:769:25)\n' +
    '    at async Bridge.getUserName (file:///home/h3c/Documents/getting-started/node_modules/wechaty-puppet-wechat/src/bridge.ts:417:24)\n' +
    '    at async PuppetWeChat.onLogin (file:///home/h3c/Documents/getting-started/node_modules/wechaty-puppet-wechat/src/event.ts:147:20)'
}
10:01:34 VERB PuppetWeChatBridge onLoad() page.url=https://wx.qq.com/cgi-bin/mmwebwx-bin/webwxnewloginpage?ticket=ATTO_kDQObI4--DESmmmhaIW@qrticket_0&uuid=gdcOJNWG5Q==&lang=en_US&scan=1674007279
10:01:34 VERB PuppetWeChatBridge readyAngular()
10:01:34 VERB PuppetWeChatBridge inject()
10:01:34 VERB PuppetWeChatBridge inject() exception: execute proxyWechaty(init) error: 503, init() without a ready angular env. stack: Error: execute proxyWechaty(init) error: 503, init() without a ready angular env
    at Bridge.inject (file:///home/h3c/Documents/getting-started/node_modules/wechaty-puppet-wechat/src/bridge.ts:356:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Bridge.onLoad (file:///home/h3c/Documents/getting-started/node_modules/wechaty-puppet-wechat/src/bridge.ts:214:7)
10:01:34 ERR PuppetWeChatBridge onLoad() exception: Error: execute proxyWechaty(init) error: 503, init() without a ready angular env
10:01:34 ERR Config ###########################
10:01:34 ERR Config Wechaty unhandledRejection: Error: execute proxyWechaty(init) error: 503, init() without a ready angular env
    at Bridge.inject (file:///home/h3c/Documents/getting-started/node_modules/wechaty-puppet-wechat/src/bridge.ts:356:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Bridge.onLoad (file:///home/h3c/Documents/getting-started/node_modules/wechaty-puppet-wechat/src/bridge.ts:214:7) [object Promise]
10:01:34 ERR Config ###########################
10:01:34 ERR Config process.on(unhandledRejection) promise.catch(execute proxyWechaty(init) error: 503, init() without a ready angular env)
Config GError: execute proxyWechaty(init) error: 503, init() without a ready angular env
    at Bridge.inject (file:///home/h3c/Documents/getting-started/node_modules/wechaty-puppet-wechat/src/bridge.ts:356:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Bridge.onLoad (file:///home/h3c/Documents/getting-started/node_modules/wechaty-puppet-wechat/src/bridge.ts:214:7) {
  code: 2,
  details: 'Error: execute proxyWechaty(init) error: 503, init() without a ready angular env\n' +
    '    at Bridge.inject (file:///home/h3c/Documents/getting-started/node_modules/wechaty-puppet-wechat/src/bridge.ts:356:15)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
    '    at async Bridge.onLoad (file:///home/h3c/Documents/getting-started/node_modules/wechaty-puppet-wechat/src/bridge.ts:214:7)'
}

**Comment by jsRuner** [comment]
me too. so  how  to  solved

**Comment by defnngj** [comment]
没有设置变量：

export WECHATY_LOG=verbose
export WECHATY_PUPPET=wechaty-puppet-padlocal    // puppet 支持多种

[Puppet](https://wechaty.gitbook.io/wechaty/puppet)  <-- 点击查看列表
