### ISSUE TITLE
Error: execute proxyWechaty(init) error: 503, init() without a ready angularenv

### ISSUE THREAD

**Issue by qixinynan** [wechaty/getting-started#289]
run in the latest google cloud shell
```bash
12:30:46 INFO StarterBot onScan: Scanned(3)
12:30:48 ERR PuppetWeChatBridge onLoad() exception: Error: execute proxyWechaty(init) error: 503, init() without a ready angularenv
file:///home/g3185835784/cloudshell_open/getting-started/node_modules/wechaty-puppet-wechat/src/bridge.ts:356
        throw new Error('execute proxyWechaty(init) error: ' + retObj?.code + ', ' + retObj?.message)
              ^
GError: execute proxyWechaty(init) error: 503, init() without a ready angular env
    at Bridge.inject (file:///home/g3185835784/cloudshell_open/getting-started/node_modules/wechaty-puppet-wechat/src/bridge.ts:356:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Bridge.onLoad (file:///home/g3185835784/cloudshell_open/getting-started/node_modules/wechaty-puppet-wechat/src/bridge.ts:214:7) {
  code: 2,
  details: 'Error: execute proxyWechaty(init) error: 503, init() without a ready angular env\n' +
    '    at Bridge.inject (file:///home/g3185835784/cloudshell_open/getting-started/node_modules/wechaty-puppet-wechat/src/bridge.ts:356:15)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
    '    at async Bridge.onLoad (file:///home/g3185835784/cloudshell_open/getting-started/node_modules/wechaty-puppet-wechat/src/bridge.ts:214:7)'
}
```

**Comment by EasonHuangkkq** [comment]
anyone solve the issue?

**Comment by qixinynan** [comment]
> anyone solve the issue?

seems no

**Comment by brucetoo** [comment]
the same here, how to resolve this ?

**Comment by zhiguoxu** [comment]
mee too
