### ISSUE TITLE
你的应用版本过低

### ISSUE THREAD

**Issue by exchangkong** [wechaty/getting-started#311]
15:10:50 VERB StateSwitch <WechatyReady> inactive(true) <- (true)
15:10:50 INFO StarterBot onScan: Scanned(3)
15:11:06 VERB StateSwitch <WechatyReady> inactive(true) <- (true)
15:11:06 INFO StarterBot onScan: Confirmed(4)
15:11:08 ERR [Request] [tid:f5b0f9cd], padlocal grpc request failed: 1, error: Error: 2 UNKNOWN: [tid:f5b0f9cd] wechat bad request error: 你的应用版本过低，请升级至最新版本后再登录。点击“确定”后将跳转至最新版下载页面。
15:11:08 ERR start client failed: VError: [tid:f5b0f9cd] request has been cancelled for reason: SERVER_ERROR: 2 UNKNOWN: [tid:f5b0f9cd] wechat bad request error: 你的应用版本过低，请升级至最新版本后再登录。点击“确定”后将跳转至最新版下载页面。
    at Request._failAllPendingRequest (/Users/kk/www/dimvector/getting-started/node_modules/padlocal-client-ts/dist/Request.js:265:19)
    at ClientDuplexStreamImpl.<anonymous> (/Users/kk/www/dimvector/getting-started/node_modules/padlocal-client-ts/dist/Request.js:56:18)
    at ClientDuplexStreamImpl.emit (node:events:519:28)
    at Object.onReceiveStatus (/Users/kk/www/dimvector/getting-started/node_modules/@grpc/grpc-js/build/src/client.js:420:28)
    at Object.onReceiveStatus (/Users/kk/www/dimvector/getting-started/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /Users/kk/www/dimvector/getting-started/node_modules/@grpc/grpc-js/build/src/resolving-call.js:129:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
15:11:11 INFO [PuppetPadlocal] start login with type: QrLogin
15:11:12 VERB StateSwitch <WechatyReady> inactive(true) <- (true)
15:11:12 INFO StarterBot onScan: Waiting(2) - https://wechaty.js.org/qrcode/http%3A%2F%2Fweixin.qq.com%2Fx%2FQbwbc56gj-QYyjtQ5PYN

**Comment by hd19820806** [comment]
同样问题，是不是项目已经挂了？

**Comment by pest1999** [comment]
我也会，时间不短了，开发组没回复，估计是挂了

**Comment by fdslk** [comment]
我也有同样的问题，这个问题都open这么久了吗？那正式版本还能用吗？这是最基础的，我用的就是demo中`ding-dong-bot.js`
